version: 2.0

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      HAB_LICENSE: accept
    steps:
      - checkout
      - run:
          name: Install Habitat
          command: |
            curl "https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh" | sudo bash
            hab origin key download --secret --auth="${HAB_AUTH_TOKEN}" pip
            hab origin key download --auth="${HAB_AUTH_TOKEN}" pip
      - run:
          name: Build Plans
          command: sudo .circleci/build.sh
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build 
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only: master

    jobs:
      - build